MODEL:
  TYPE: regionvit
  NAME: regionvit_small_patch4_window7_224
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 8, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
  REGION_VIT:
    LOCAL_TOKENIZATION_METHOD: 3-conv
    REGIONAL_TOKENIZATION_METHOD: linear
